name: SQL Execution CI

on:
  workflow_dispatch:
jobs:
  sql-execution:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: healthcare_dw
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install MySQL client
      run: sudo apt-get install -y mysql-client

    - name: Wait for MySQL
      run: |
        until mysqladmin ping -h 127.0.0.1 -proot --silent; do
          echo "Waiting for MySQL..."
          sleep 5
        done

    - name: Execute schema SQL
      run: |
         mysql -h 127.0.0.1 -uroot -proot healthcare_dw <<'EOF'
         USE healthcare_dw;

         CREATE TABLE IF NOT EXISTS stg_hospital_readmission (
              patient_id VARCHAR(10),
              age INT,
              age_group VARCHAR(10),
              gender VARCHAR(10),
              department VARCHAR(50),
              diagnosis VARCHAR(50),
              length_of_stay INT,
              num_medications INT,
              num_procedures INT,
              admission_type VARCHAR(20),
              discharge_disposition VARCHAR(20),
              readmitted VARCHAR(5)
              );
              EOF
       
            mysql -h 127.0.0.1 -uroot -proot healthcare_dw < sql/dimension_tables.sql
            mysql -h 127.0.0.1 -uroot -proot healthcare_dw < sql/fact_tables.sql

    - name: Execute analysis queries
      run: |
        mysql -h 127.0.0.1 -uroot -proot healthcare_dw < sql/analysis_queries.sql
